services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    networks:
      - siopal
    depends_on:
      - mysql
  mysql:
    image: mysql:lts
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      # MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - siopal

networks:
  siopal:
    driver: bridge
